### PR TITLE
Add "run on replit" badge

### PR DESCRIPTION
**Pull request by Scoder12**
This is a really cool game!

I added a badge that allows users to run the game in the browser on [repl.it](https://repl.it). This is what it will look like:
image
image

### CODE REVIEW

**Comment by vaniacer** [comment]
Thank you!)

**Comment by vaniacer** [comment]
Got permission denied on run(

**Comment by vaniacer** [comment]
Fixit.

**Comment by Scoder12** [comment]
@vaniacer the way it works is by cloning the repo and reading the `.replit` file so it won't work until its merged

**Pull request merged**
